export { default as accountReducer } from './accountSlice'
export { default as cartReducer } from './cartSlice'
export { default as brandReducer } from './brandSlice'
export { default as detailProductReducer}  from './detailProductSlice'
export { default as addressProductReducer}  from './addressSlice'
export { default as orderReducer}  from './orderSlice'
export { default as commentReducer}  from './commentSlice'