export { default as  DefaultLayout}  from './DefaultLayout'
export { default as LayoutNoHeader}  from './LayoutNoHeader'
export { default as LayoutCategoryProduct}  from './LayoutCategoryProduct'
export { default as LayoutClientNoSidebar}  from './LayoutClientNoSidebar'
export { default as MainLayout}  from './MainLayout'
export { default as LayoutCheckout}  from './LayoutCheckout'
export { default as LayoutAccount}  from './LayoutAccount'
